export const SET_OPERATION_IN_PROGRESS = 'SET_OPERATION_IN_PROGRESS';
export const SET_IN_LINE_OPERATION_IN_PROGRESS = 'SET_IN_LINE_OPERATION_IN_PROGRESS';

export const UPLOAD_FILE_OPEN = 'UPLOAD_FILE_OPEN';

export const SET_CREATE_PROJECT_NAME = 'SET_CREATE_PROJECT_NAME';
export const SET_CREATE_PROJECT_DESCRIPTION = 'SET_CREATE_PROJECT_DESCRIPTION';
export const SET_CREATE_PROJECT_ASSOCIATED_COMPANY = 'SET_CREATE_PROJECT_ASSOCIATED_COMPANY';
export const RESET_CREATE_PROJECT = 'RESET_CREATE_PROJECT';

export const SET_CREATE_TICKET_NAME = 'SET_CREATE_TICKET_NAME';
export const SET_CREATE_TICKET_PRIORITY = 'SET_CREATE_TICKET_PRIORITY';
export const SET_CREATE_TICKET_ASSIGNEE = 'SET_CREATE_TICKET_ASSIGNEE';
export const SET_CREATE_TICKET_PROJECT = 'SET_CREATE_TICKET_PROJECT';
export const SET_CREATE_TICKET_DESCRIPTION = 'SET_CREATE_TICKET_DESCRIPTION';
export const RESET_CREATE_TICKET = 'RESET_CREATE_TICKET';

export const SET_TOKEN = 'SET_TOKEN';
