export const SET_OPERATION_IN_PROGRESS = 'SET_OPERATION_IN_PROGRESS';
export const SET_IN_LINE_OPERATION_IN_PROGRESS = 'SET_IN_LINE_OPERATION_IN_PROGRESS';

export const SET_CREATE_PROJECT_NAME = 'SET_CREATE_PROJECT_NAME';
export const SET_CREATE_PROJECT_DESCRIPTION = 'SET_CREATE_PROJECT_DESCRIPTION';
export const SET_CREATE_PROJECT_ASSOCIATED_COMPANY = 'SET_CREATE_PROJECT_ASSOCIATED_COMPANY';
